spring:
  application:
    name: Kafka Demo
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: SASL_PLAINTEXT
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required \
            username="app" \
            password="app_secret";
    consumer:
      group-id: my-group-id
      auto-offset-reset: earliest
      properties:
        enable.auto.commit: false
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    template:
      default-topic: demo_topic
