# docker-compose.kafka-kraft.yml
version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest   # or pin: 3.7.0
    container_name: kafka-kraft
    ports:
      - "9092:9092"      # client (PLAINTEXT)
      - "9093:9093"      # internal listener
    environment:
      # KRaft cluster bootstrap:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Listeners → map external → internal
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"   # Bitnami helper
      # (Optional) create a topic automatically
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kraft_data:/bitnami/kafka
volumes:
  kraft_data:
